### ISSUE TITLE
Trying to join game, stuck on processing handshake protocol

### ISSUE THREAD

**Issue by proudno0b** [TheSaminator/kriegsspiel-online#2]
may have something to do with this console output (but doubt it)
DevTools failed to load source map: Could not load content for https://hammerjs.github.io/dist/hammer.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by proudno0b** [comment]
I was using chrome, friend was using firefox

**Comment by TheSaminator** [comment]
Alright, I think I fixed it.

The problem was caused by your friend joining your game before you've clicked the "Continue" button. The game originally only opened the peer connection after that button is clicked, so when your friend joined, the game client attempted connecting to the equivalent of a brick wall.

It was a bit counterintuitive for the game to do that, so now it won't require you to click anything before you can send your game ID to your friend.
